# Generated by Django 6.0.7 on 2026-07-27 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('required_skills', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('vacancies', models.PositiveIntegerField()),
                ('job_type', models.CharField(choices=[('Full Time', 'Full Time'), ('Internship', 'Internship'), ('Part Time', 'Part Time')], max_length=20)),
                ('last_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='companies.companyprofile')),
            ],
        ),
    ]
