# Generated by Django 6.0.7 on 2026-07-26 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('college_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('passing_year', models.IntegerField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('address', models.TextField()),
                ('resume', models.FileField(upload_to='resumes/')),
                ('profile_picture', models.ImageField(upload_to='profile_pictures/')),
                ('skills', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
